# Generated by Django 2.0.3 on 2018-05-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180514_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='name',
            field=models.CharField(max_length=20, verbose_name='城市名'),
        ),
    ]
