# Generated by Django 2.0.3 on 2018-07-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180716_1446'),
        ('courses', '0002_auto_20180514_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='organization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
